### ISSUE TITLE
Collaboration

### ISSUE THREAD

**Issue by jasonmit** [bobisjan/ember-format#36]
Hi @bobisjan,

I reach out to you awhile back around collaborating behind one of the formatjs solution and then we lost communication.  Are you still open to this?  I'd like to share some ideas if you are.

I'm currently maintaining https://github.com/yahoo/ember-intl/

**Comment by bobisjan** [comment]
Hi Jason,

I'm sorry that the connection was lost because I didn't have time for free projects due to paid ones.

The situation is going to be more relaxed at my work so I'm looking forward to contribute.

As of the official integration I'm going to deprecated my implementation as a first step...

Jan

**Comment by jasonmit** [comment]
:+1: ping me if you want to chat about some of the future ideas of ember-intl :)
